language: android

android:
    components:
        - tools
        - build-tools-23.0.2
        - android-23
        - extra
        
script:
    - bash cd UnitySplashScreen/Android && gradlew makeJar
    
